### ISSUE TITLE
Help needed: understanding get_key function

### ISSUE THREAD

**Issue by e-ivkov** [jeromefroe/hashring-rs#10]
I am having trouble understanding this transformation:

```rust
    let hash = hasher.finish();

    let buf = hash.to_be_bytes();

    u64::from(buf[7]) << 56
        | u64::from(buf[6]) << 48
        | u64::from(buf[5]) << 40
        | u64::from(buf[4]) << 32
        | u64::from(buf[3]) << 24
        | u64::from(buf[2]) << 16
        | u64::from(buf[1]) << 8
        | u64::from(buf[0])
```

hasher.finish() returns a u64 hash, so why not just return it? What are the conversions after it doing? Seems like they are reversing the bytes, but why is it needed?

Originally posted at https://github.com/jeromefroe/hashring-rs/issues/6#issuecomment-1055257818

P.S. It is not a critique, just trying to understand the algorithm logic as I am comparing this library with other consistent hashing libraries.

**Comment by e-ivkov** [comment]
I tried removing the transformation part and the distribution of points as shown in one of the tests remains roughly the same.

**Comment by jeromefroe** [comment]
Hey @e-ivkov! You bring up a great point, this logic is actually no longer needed. It was necessary in the initial commit since originally the hash was written to a buffer of bytes and we needed to turn that buffer into a `u64`. However, #3 updated the library to use the `Hasher` trait which returns a `u64` and makes this transformation unnecessary. It was just an oversight that we didn't remove the transformation in that PR as well 🤦

**Comment by e-ivkov** [comment]
Thanks a lot for clarification and fixing this!
